---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без. 
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - На странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты.
non-functional:
  - Магазин должен быть SPA приложением, которое не перезагружает страницу.
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - при постраничном просмотре каталога должен отображаться номер текущей страницы
  - при фильтрации или поиску по каталогу должно отображаться колчество товаров, соответствующих критериям поиска или фильтрации 
  - в заголовке сайте должна быть указана контактная информация продавца (или телефон call-центра)
  - на сайте должна быть указана юридическая информация о продавце
  - на сайте должна быть указана информация о разработчике сайта
 

